### ISSUE TITLE
Reversed date

### ISSUE THREAD

**Issue by jenstornell** [molocLab/kirby-calendar-board#12]
I don't know why but the date is reversed. I expected it to be 2017-02-02 in the title field. Instead it says 02-02-2017.

![image](https://cloud.githubusercontent.com/assets/927011/12787767/1fb2e8ec-ca97-11e5-9b68-2748a102254b.png)

**Comment by molocLab** [comment]
Ehehehe :).

You see reverted date because you are swedish.
For me and for most of the world that is the right way. ([Wikipedia](https://en.wikipedia.org/wiki/Calendar_date#Gregorian.2C_day-month-year_.28DMY.29))

I used yyyy-mm-dd notation just in slugs because it is useful for sorting.

Maybe, in a future release, I'll add an option for date format.
If you want to change it, it's super easy:

calendarboard.php -> row 127:
change:
'title' => $date_friendly
with
'title' => $day

It's just a label so it will not break anything (I hope :P)

**Comment by jenstornell** [comment]
But what!!? We don't have dates like that in Sweden. Never ever. But I see that it's not your fault.

This is our biggest bank in Sweden (they just skipped the dashes).

![image](https://cloud.githubusercontent.com/assets/927011/12808621/8fcfbc82-cb18-11e5-92e8-a631b05eb413.png)

Closing it because it's not a bug here.
